<?php
if (is_array($news)) {
	if (empty($news)) {
		echo '<p>'.$textNoNews.'</p>';
	} else {
		echo '<div style="max-height: 200px; overflow: auto;">';
		echo '<ul>';
		foreach ($news as $item) {
			echo '<li>';
			echo '<a href="'.$item['link'].'" target="_blank">'.$item['title'].'</a>';
			echo '</li>';
		}
		echo '</ul>';
		echo '</div>';
	}
} else {
	echo '<p>'.$news.'</p>';
}
?>