<?php if (is_array($news)) { ?>
	<?php if (empty($news)) echo '<br /><br /><br /><br /><br /><p>'.$textNoNews.'</p>'; ?>
	<?php foreach ($news as $item) { ?>
		<div class="item">
			<p class="date"><?php echo date('j F Y, H:i', strtotime($item['pubDate'])); ?></p>
			<h2><a href="<?php echo $item['link']; ?>" target="_blank"><?php echo $item['title']; ?></a></h2>
			<p><?php echo str_replace('Read more', ' <a href="'.$item['link'].'" target="_blank">Read more</a>', strip_tags($item['description'])); ?></p>
		</div>
	<?php } ?>
<?php } else { ?>
	<p><?php echo $news; ?></p>
<?php } ?>
