<!--rabbit "hello"-->
<img src="<?php echo  $imgPath . "hello.png"; ?>" id="sharexy_hello">
<!--end rabbit "hello"-->


<!--logo+text-->
<h2 class="sharexy_h2" align="center">
    <?php echo $logoSRC ? "<a href='http://sharexy.com/' target='_blank'><img src='" . $logoSRC . "'></a>" : ''; ?>
</h2>
<!--end logo+text-->

<!-- Tabs -->
<div class="tabs">
	<div class="tab"><a href="?page=sharexy-menu">Sharing tool</a></div>
	<div class="tab active">Network Buzz</div>
</div>

<!--promo-->
<table cellspacing="5" border="0" class="sharexy_promo">
    <tr>
        <td>
            <div class="sharexy_facebook_like bt" style="overflow: visible">
                <div class="sharexy_promo_text">Do you like this plugin?</div>
                <table cellspacing="0" border="0">
                    <tr>
                        <td align="left">
                            <?php echo "<img src='" . $imgPath . "facebook.png'>";?>
                        </td>
                        <td align="center">
                            <a href="javascript: var uri = encodeURIComponent('http://su.pr/1UMmRl'); var title=encodeURIComponent('Sharexy - powerful social sharing, bookmarking and blog monetization tool'); window.open('http://www.facebook.com/sharer.php?u='+uri+'&t='+title ,null, 'toolbar=0, location=0, directories=0, status=0, menubar=0, scrollbars=0, resizable=0, width=850, height=750');void(0);">
                                <?php echo "<img src='" . $imgPath . "like.png'>";?>
                            </a>
                        </td>
                    </tr>
                </table>
            </div>
        </td>
        <td>
            <div class="sharexy_twitter_like bt">

                <div class="sharexy_promo_text">Tweet about Plugin</div>
                <div style="padding-left: 38px; width: 40px;">
                    <a href="javascript: var uri = encodeURIComponent('http://su.pr/1UMmRl'); var title=encodeURIComponent('Sharexy - powerful social sharing, bookmarking and blog monetization tool'); window.open('http://twitter.com/share?url='+uri+'&text='+title ,null, 'toolbar=0, location=0, directories=0, status=0, menubar=0, scrollbars=0, resizable=0, width=850, height=750');void(0);">
                        <?php echo "<img src='" . $imgPath . "tweet.png'>";?>
                    </a>
                </div>
            </div>
        </td>
        <td>
            <div class="sharexy_fan bt" style="width: 145px; overflow: visible">

                <div class="sharexy_promo_text">Recommend plugin</div>
                <div style="padding: 2px 0 0 48px; width: 40px;">
                    <a href="javascript: var uri = encodeURIComponent('http://wordpress.org/extend/plugins/sharexy/'); window.open('https://plusone.google.com/_/+1/confirm?hl=en&url='+uri ,null, 'toolbar=0, location=0, directories=0, status=0, menubar=0, scrollbars=0, resizable=0, width=850, height=750');void(0);">
                        <?php echo "<img src='" . $imgPath . "google_plus.png'>";?>
                    </a>
                </div>
            </div>
        </td>
        <td>
            <div class="sharexy_fan bt" style="width: 240px; overflow: visible">
                <div class="sharexy_promo_text">Become a Sharexy Fan</div>
                <table style='margin-left: 9px' cellspacing="2" cellpadding="0" border="0">
                    <tr>
                        <td valign="top">
                            <div>
                                <a href="https://plus.google.com/104782962930304985256" target="_blank"><img
                                        src="<?php echo  $imgPath . "Google-Plus.png"; ?>"></a>
                            </div>
                        </td>
                        <td valign="top">
                            <a href="https://twitter.com/sharexy_com" class="twitter-follow-button"
                               data-show-count="false" data-lang="en">Follow</a>

                            <script>!function(d, s, id) {
                                var js,fjs = d.getElementsByTagName(s)[0];
                                if (!d.getElementById(id)) {
                                    js = d.createElement(s);
                                    js.id = id;
                                    js.src = "//platform.twitter.com/widgets.js";
                                    fjs.parentNode.insertBefore(js, fjs);
                                }
                            }(document, "script", "twitter-wjs");</script>

                        </td>
                        <td valign="top" style="padding-top: 1px;">
                            <a href="javascript: var uri = encodeURIComponent('http://sharexy.com/'); var title=encodeURIComponent('Sharexy - Sharing widget, Share Button, Social Bookmark, Sharing Plugins, Analytics, Blog and website monetization tool.'); window.open('http://www.facebook.com/sharer.php?u='+uri+'&t='+title ,null, 'toolbar=0, location=0, directories=0, status=0, menubar=0, scrollbars=0, resizable=0, width=850, height=750');void(0);">
                                <?php echo "<img src='" . $imgPath . "like.png'>";?>
                            </a>
                        </td>
                    </tr>
                </table>


            </div>
        </td>
        <td>
            <div class="sharexy_rating bt">
                <div class="sharexy_promo_text"> Give Us a</div>
                <a target="_blank" class="rating" href="http://wordpress.org/extend/plugins/sharexy/" class="rating">perfect
                    rating</a>

            </div>
        </td>

        <td>
            <!---- Ask a question, leave feedback or share your ideasg-->
            <div class="sharexy_feedback bt">
                <a target="_blank" class="sharexy_promo_text" href="http://community.sharexy.com">Ask a question, leave
                    feedback
                    or share your ideas</a>

            </div>
            <!---end -Ask a question, leave feedback or share your ideas-->
        </td>
    </tr>
</table>
<!--end promo-->

<div class="sharexy_content"><div class="sharexy_content_pd">
<div id="PromoTop">
	<div class="left"><span>Do you want to see your post here?</span> As well as thousands of other bloggers on thousands of other blogs.</div>
	<div class="right"><a href="http://sharexy.com/registration/?utm_source=feed_plugin_button" target="_blank"></a></div>
</div>
<div id="SharexyCommunityRight">
	<div id="SharexyPromo"><div id="SharexyPromoInner">
		<div class="promo-title">Sharexy — </div>
		<div class="promo-text1">the place where blogging becomes social</div>
		<div class="promo-text2">Publish articles, news, links and put them in front of eyes of thousands bloggers and readers</div>
		<div class="promo-text2">Read and share useful information about your own interest</div>
		<div class="promo-text2">Connect with other people and expand the circle of friends, your blog readers and potential clients</div>
		<div class="promo-text2">Promote yourself and your blog for <span>Free</span></div>
		<div class="promo-text2">Receive donations from Your readers</div>
		<div class="promo-text2">Advertise third-party products or sevices in your posts <small>(Pro plan trial)</small></div>
		<div class="promo-text2">Spread the world about your blog updates,<br />Get more traffic and new readers</div>
	</div></div>
	<div id="SharexyCommunityInfo">This tool allows you to see what other bloggers are posting in the categories of your interest and to be updated with the latest news and trends.</div>
	
	<script type='text/javascript'>
	var _ues = {
	host:'sharexy.userecho.com',
	forum:'11680',
	lang:'en',
	tab_show:false,
	};
	
	(function() {
	    var _ue = document.createElement('script'); _ue.type = 'text/javascript'; _ue.async = true;
	    _ue.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.userecho.com/js/widget-1.4.gz.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(_ue, s);
	})();
	</script>
	<p style="font-size: 22px; text-align: center;"><a onmouseover="UE.Popin.preload();" href="#" onclick="UE.Popin.show(); return false;">Leave Feedback</a></p>
</div>

<script type="text/javascript">
function loadNews() {
	jQuery('#News').hide();
	jQuery('#HubLoader').show();
	var rss = jQuery('#SelectHub').val();
	jQuery.post('<?php echo $_SERVER['REQUEST_URI']; ?>', {'rss': rss, 'ajax': 1},
		function(data) {
			jQuery('#News').html(data);
			jQuery('#HubLoader').hide();
			jQuery('#News').show();
		},
		'html');
}
jQuery(document).ready(function() { loadNews(); });
</script>

<div id="NewsContainer">
	<div class="clr">
		<div id="HubSelector">
			Choose a Hub:
			<select id="SelectHub" onchange="loadNews();">
				<?php foreach ($rssarr as $id => $val) { ?>
					<option value="<?php echo $id; ?>" <?php if ($id == $rssId) echo 'selected="selected"'; ?>><?php echo $val['title']; ?></option>
				<?php } ?>
			</select>
		</div>
	</div>
	<div id="HubLoader"><img src="<?php echo  $imgPath . "loading.gif"; ?>" /></div>
	<div id="News"></div>
</div>

</div></div>

<script type="text/javascript" src="<?php echo WP_PLUGIN_URL . '/sharexy/js/constructor.js' ?>"></script>
<link rel="stylesheet" type="text/css" href="<?php echo WP_PLUGIN_URL . '/sharexy/css/constructor.css'?>" media="screen"/>

<script type="text/javascript" src="http://stat.trafficgate.org/feed_plugin.html"></script>