<!--rabbit "hello"-->
<img src="<?php echo  $imgPath . "hello.png"; ?>" id="sharexy_hello">
<!--end rabbit "hello"-->


<!--logo+text-->
<h2 class="sharexy_h2" align="center">
    <?php echo $logoSRC ? "<img src='" . $logoSRC . "'>" : ''; ?>
</h2>
<!--end logo+text-->

<div id="sharexy_fuzz"></div>

<!--promo-->
<table cellspacing="5" border="0" class="sharexy_promo">
    <tr>
        <td>
            <div class="sharexy_facebook_like bt" style="overflow: visible">
                <div class="sharexy_promo_text">Do you like this plugin?</div>
                <table cellspacing="0" border="0">
                    <tr>
                        <td align="left">
                            <?php echo "<img src='" . $imgPath . "facebook.png'>";?>
                        </td>
                        <td align="center">
                            <a href="javascript: var uri = encodeURIComponent('http://su.pr/1UMmRl'); var title=encodeURIComponent('Sharexy - powerful social sharing, bookmarking and blog monetization tool'); window.open('http://www.facebook.com/sharer.php?u='+uri+'&t='+title ,null, 'toolbar=0, location=0, directories=0, status=0, menubar=0, scrollbars=0, resizable=0, width=850, height=750');void(0);">
                                <?php echo "<img src='" . $imgPath . "like.png'>";?>
                            </a>
                        </td>
                    </tr>
                </table>
            </div>
        </td>
        <td>
            <div class="sharexy_twitter_like bt">

                <div class="sharexy_promo_text">Tweet about Plugin</div>
                <div style="padding-left: 38px; width: 40px;">
                    <a href="javascript: var uri = encodeURIComponent('http://su.pr/1UMmRl'); var title=encodeURIComponent('Sharexy - powerful social sharing, bookmarking and blog monetization tool'); window.open('http://twitter.com/share?url='+uri+'&text='+title ,null, 'toolbar=0, location=0, directories=0, status=0, menubar=0, scrollbars=0, resizable=0, width=850, height=750');void(0);">
                        <?php echo "<img src='" . $imgPath . "tweet.png'>";?>
                    </a>
                </div>
            </div>
        </td>
        <td>
            <div class="sharexy_fan bt" style="width: 145px; overflow: visible">

                <div class="sharexy_promo_text">Recommend plugin</div>
                <div style="padding: 2px 0 0 48px; width: 40px;">
                    <a href="javascript: var uri = encodeURIComponent('http://wordpress.org/extend/plugins/sharexy/'); window.open('https://plusone.google.com/_/+1/confirm?hl=en&url='+uri ,null, 'toolbar=0, location=0, directories=0, status=0, menubar=0, scrollbars=0, resizable=0, width=850, height=750');void(0);">
                        <?php echo "<img src='" . $imgPath . "google_plus.png'>";?>
                    </a>
                </div>
            </div>
        </td>
        <td>
            <div class="sharexy_fan bt" style="width: 240px; overflow: visible">
                <div class="sharexy_promo_text">Become a Sharexy Fan</div>
                <table style='margin-left: 9px' cellspacing="2" cellpadding="0" border="0">
                    <tr>
                        <td valign="top">
                            <div>
                                <a href="https://plus.google.com/104782962930304985256" target="_blank"><img
                                        src="<?php echo  $imgPath . "Google-Plus.png"; ?>"></a>
                            </div>
                        </td>
                        <td valign="top">
                            <a href="https://twitter.com/sharexy_com" class="twitter-follow-button"
                               data-show-count="false" data-lang="en">Follow</a>

                            <script>!function(d, s, id) {
                                var js,fjs = d.getElementsByTagName(s)[0];
                                if (!d.getElementById(id)) {
                                    js = d.createElement(s);
                                    js.id = id;
                                    js.src = "//platform.twitter.com/widgets.js";
                                    fjs.parentNode.insertBefore(js, fjs);
                                }
                            }(document, "script", "twitter-wjs");</script>

                        </td>
                        <td valign="top" style="padding-top: 1px;">
                            <a href="javascript: var uri = encodeURIComponent('http://sharexy.com/'); var title=encodeURIComponent('Sharexy - Sharing widget, Share Button, Social Bookmark, Sharing Plugins, Analytics, Blog and website monetization tool.'); window.open('http://www.facebook.com/sharer.php?u='+uri+'&t='+title ,null, 'toolbar=0, location=0, directories=0, status=0, menubar=0, scrollbars=0, resizable=0, width=850, height=750');void(0);">
                                <?php echo "<img src='" . $imgPath . "like.png'>";?>
                            </a>
                        </td>
                    </tr>
                </table>


            </div>
        </td>
        <td>
            <div class="sharexy_rating bt">
                <div class="sharexy_promo_text"> Give Us a</div>
                <a target="_blank" class="rating" href="http://wordpress.org/extend/plugins/sharexy/" class="rating">perfect
                    rating</a>

            </div>
        </td>

        <td>
            <!---- Ask a question, leave feedback or share your ideasg-->
            <div class="sharexy_feedback bt">
                <a target="_blank" class="sharexy_promo_text" href="http://community.sharexy.com">Ask a question, leave
                    feedback
                    or share your ideas</a>

            </div>
            <!---end -Ask a question, leave feedback or share your ideas-->
        </td>
        <td>
            <div class="yepty_banner bt" onclick="window.open('http://yepty.com')">
            </div>
        </td>


    </tr>
</table>
<!--end promo-->
<div class="sharexy_content">
<div class="sharexy_content_pd">
    <h3 class="sharexy_h3">Sharexy account settings </h3>

    <form action='' method='post' id='sharexy_plugin_constructor_form'>
        <a class="tips" id="publisher_key">Publisher key</a> <span class="gray">(optional)</span>
        <input type='text' id="user_id" name='user_id'
               value='<?php echo $styleParams['user_id'] ? $styleParams['user_id'] : '';?>'>
        <br><img style="display: none" src="<?php echo  $imgPath . "publisher_key.png"; ?>" id="publisher_key_img">

        <div id="fail_user_id"
             style='margin-top: 5px;display:none; background: none repeat scroll 0 0 #FFFFE4;border: 1px solid #FFBC9F;color: #ff0000;font-size: 12px;line-height: 20px;margin-bottom: 20px;padding: 3px 7px;text-align: center;'>
            Incorrect ID
        </div>
        <div class="sharexy_desc">
            If you are not registered at Sharexy yet, take a few seconds to <a href="http://sharexy.com/?registration=1" target="_blank">register</a> and start earning with us, access your stats and receive your earnings directly into your Paypal account every 15 days.
        </div>


    <h4 style="margin-bottom: 0;">
                <span class="niceCheck"><input type='checkbox' id='translation_popup_bot_a'
                                               class='ads_translation_settings'
                                               id="popup_bot_a"
                                               name='popup_bot_a' <?php echo (int)$styleParams['popup_bot_a'] == 1 ? "value='1' checked='true'" : " value='0' ";?>></span>
        <a class="tips"
           style="text-decoration: none; border-bottom: 1px dotted #C7531F !important; color: #C7531F !important;"><label
                for="translation_popup_bot_a">Help other good people find our website by displaying Sharexy link</label></a>
    </h4>
	
	<br />
	<a href="http://sharexy.com/about_traffic_miner" target="_blank">Find out More about TrafficMiner widget</a>
	<br />
	
	<h2>TrafficMiner settings</h2>
	<div id="tm_settings">

		<h3 class="sharexy_h3">Placement</h3>
		<span>Please select locations where you want to display TrafficMiner widget</span><br />
	
		<div class="tm_option">
		<span class="niceCheck"><input type='checkbox' id='translation_tm_place_home'
                                               class='ads_translation_settings'
                                               id="tm_place_home"
                                               name='tm_place_home' <?php echo (int)$styleParams['tm_place_home'] == 1 ? "value='1' checked='true'" : " value='0' ";?>></span>
			<label for="translation_tm_place_home">Home page</label>
		</div>
		
		<div class="tm_option">
		<span class="niceCheck"><input type='checkbox' id='translation_tm_place_single'
                                               class='ads_translation_settings'
                                               id="tm_place_single"
                                               name='tm_place_single' <?php echo (int)$styleParams['tm_place_single'] == 1 ? "value='1' checked='true'" : " value='0' ";?>></span>
			<label for="translation_tm_place_single">Single post</label>
		</div>
		
		<div class="tm_option">
		<span class="niceCheck"><input type='checkbox' id='translation_tm_place_page'
                                               class='ads_translation_settings'
                                               id="tm_place_page"
                                               name='tm_place_page' <?php echo (int)$styleParams['tm_place_page'] == 1 ? "value='1' checked='true'" : " value='0' ";?>></span>
			<label for="translation_tm_place_page">Page</label>
		</div>
		
		<div class="tm_option">
		<span class="niceCheck"><input type='checkbox' id='translation_tm_place_archive'
                                               class='ads_translation_settings'
                                               id="tm_place_archive"
                                               name='tm_place_archive' <?php echo (int)$styleParams['tm_place_archive'] == 1 ? "value='1' checked='true'" : " value='0' ";?>></span>
			<label for="translation_tm_place_archive">Archive</label>
		</div>	
		
		<div class="tm_option">
		<span class="niceCheck"><input type='checkbox' id='translation_tm_place_attachment'
                                               class='ads_translation_settings'
                                               id="tm_place_attachment"
                                               name='tm_place_attachment' <?php echo (int)$styleParams['tm_place_attachment'] == 1 ? "value='1' checked='true'" : " value='0' ";?>></span>
				<label for="translation_tm_place_attachment">Attachment</label>
		</div>
		
		<div class="tm_option">
		<span class="niceCheck"><input type='checkbox' id='translation_tm_place_excerpt'
                                               class='ads_translation_settings'
                                               id="tm_place_excerpt"
                                               name='tm_place_excerpt' <?php echo (int)$styleParams['tm_place_excerpt'] == 1 ? "value='1' checked='true'" : " value='0' ";?>></span>
					<label for="translation_tm_place_excerpt">Excerpt</label>
		</div>
					
	
	
        <div id='sharexy_ads_translation_settings'>
            <h3 class="sharexy_h3">Ad broadcasting settings</h3>
            
        <span class="niceCheck" style="margin-top: 2px;"><input type='checkbox' id='translation_show_ads'
                                                                class='ads_translation_settings show_mode'
                                                                name='show_ads' <?php echo $styleParams['show_ads'] ? "value='1' checked='true'" : " value='0' ";?> /></span>

                <label for="translation_show_ads">Display ads</label>
            

        </div>
		
		<div>
			<h3 class="sharexy_h3">Appereance settings</h3>
			<div id="settings_block">
			
				<span class="appereancesettings">Background color: </span>
				<input type="radio" name="tm_bg_color" value="#fff" <?php if($styleParams['tm_bg_color'] == '#fff'){ ?> checked="checked" <?php } ?> /> White  
				<input type="radio" name="tm_bg_color" value="none"  <?php if($styleParams['tm_bg_color'] == 'none'){ ?> checked="checked" <?php } ?> /> Transparent
				
				<span class="appereancesettings" style="margin-left:60px;">Widget width: </span> <input type='text' name='tm_widget_width' id="tm_widget_width" size="4" value='<?php echo $styleParams['tm_widget_width'] ;?>' /> <span class="appereancesettings">Px</span>
				
				<span class="appereancesettings" style="margin-left:60px;">Label: </span> <input type='text' name='tm_label' id="tm_label" value='<?php echo wp_kses_stripslashes( $styleParams['tm_label'] ) ;?>' placeholder="You might also like:" />
				
			</div>
		</div>	
		
		<div id="tm_noteblock">
			<p><b>You will receive traffic only to pages that  have the widget installed.</b></p>
			<p>Please allow some time for the widget to collect information on your blog and build a list with links to relevant content.</p>
			<p>To display TrafficMiner widget in sidebar, please go to the Widgets section and activate TrafficMiner widget.</p>
		</div>
		
		<br />
		<input type='hidden' name='sel' value='sharexy_save_trafficminer_data' />
		<input type='hidden' name='tm_hide_temp_message' value='1' />
		<input type='submit' value='Save settings' id='sharexy_plugin_constructor_form_submit_button' />
		</form>
	</div>
</div>


<input type="hidden" id="SharexyImgPath" value="<?php echo $imgPath; ?>">
<input type="hidden" id="ScriptPathImg" value="<?php echo $scriptPath . 'design/'; ?>">




<script type="text/javascript" src="<?php echo WP_PLUGIN_URL . '/sharexy/js/nicecheckbox.js'; ?>"></script>
<script type="text/javascript" src="<?php echo WP_PLUGIN_URL . '/sharexy/js/niceradio.js' ?>"></script>
<script type="text/javascript" src="<?php echo WP_PLUGIN_URL . '/sharexy/js/tipsy/jquery.tipsy.js' ?>"></script>

<link rel="stylesheet" type="text/css" href="<?php echo WP_PLUGIN_URL . '/sharexy/js/farbtastic/farbtastic.css'?>"
      media="screen"/>
<link rel="stylesheet" type="text/css" href="<?php echo WP_PLUGIN_URL . '/sharexy/css/tipsy.css'?>" media="screen"/>
<link rel="stylesheet" type="text/css" href="<?php echo WP_PLUGIN_URL . '/sharexy/css/constructor.css'?>" media="screen"/>

<script type="text/javascript" src="<?php echo WP_PLUGIN_URL . '/sharexy/js/tm.js' ?>"></script>
<link rel="stylesheet" type="text/css" href="<?php echo WP_PLUGIN_URL . '/sharexy/css/tm.css'?>" media="screen"/>

<div style="clear:both"> </div>